[project]
name = "lastuuid"
version = "0.2.2"
description = "Fast UUIDv7 Compatible with standard library type, and utils."
readme = "README.md"
license = { text = "MIT License" }
authors = [{ name = "Guillaume Gauvrit", email = "guillaume@gauvr.it" }]
requires-python = ">=3.9"
keywords = ["uuid", "UUIDv7"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/mardiros/lastuuid"
Documentation = "https://mardiros.github.io/lastuuid/"
Repository = "https://github.com/mardiros/lastuuid.git"
Issues = "https://github.com/mardiros/lastuuid/issues"
Changelog = "https://mardiros.github.io/lastuuid/changelog.html"

[tool.uv]
default-groups = []

# used by sphinx-notes/pages@v3
[project.optional-dependencies]
docs = [
    "furo >=2024.5.6",
    "linkify-it-py >=2.0.3,<3",
    "myst-parser >=3.0.0,<4; python_version < '3.10'",
    "myst-parser >=4.0.0,<5; python_version >= '3.10'",
    "sphinx >=7.0.1,<8",
    "sphinx-autodoc2 >=0.5.0,<1",
]

[dependency-groups]
dev = ["pip>=24.2", "mypy>=1.4.0,<2", "pytest>=8,<9", "pydantic>=2.7.0,<3"]
docs = [
    "sphinx>=7.0.0",
    "sphinx-autodoc2 >=0.5.0,<1",
    "furo>=2024.8.6",
    "linkify-it-py >=2.0.3,<3",
    "myst-parser >=3.0.0,<4; python_version < '3.10'",
    "myst-parser >=4.0.0,<5; python_version >= '3.10'",
]

[tool.maturin]
bindings = "pyo3"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
